In [1]:
# Parse Cobb County
# Author: Peter Scarbrough
# Date: 2020-01-12

In [2]:
# load required packages
import pandas as pd

In [4]:
df = pd.read_csv("cobb-county-ga-addresses.csv")
output_df = df[["CompleteStreetName", "ZipCode", "City", "State"]]
output_df = output_df.rename(columns={
    "City": "CITY",
    "State": "STATE",
    "CompleteStreetName": "ADDRESS",
    "ZipCode": "ZIP OR POSTAL CODE"
}).dropna()
output_df["ADDRESS"] = output_df.apply(lambda x: x["ADDRESS"].upper(), axis=1)
output_df["CITY"] = output_df.apply(lambda x: x["CITY"].upper(), axis=1)
output_df["STATE"] = output_df.apply(lambda x: x["STATE"].upper(), axis=1)
output_df.to_csv("cobb-county-ga-addresses-PARSED.csv", index=False)
output_df.head(10)

               ADDRESS ZIP OR POSTAL CODE            CITY STATE
0        TRIVIEW SQ SE         30339-4920         ATLANTA    GA
1           ROXY CT NW              30101         ACWORTH    GA
2        MASTERS CT NW              30144        KENNESAW    GA
3      W VILLAGE PL SE              30080          SMYRNA    GA
4      CREIGHTON LN SE              30008        MARIETTA    GA
5    LONGSHADOW TRL SW         30082-3540          SMYRNA    GA
6        ROBERTA DR SW         30008-3804        MARIETTA    GA
7         ECTOR CHS NW         30152-4790        KENNESAW    GA
8  HEATHERBROOKE LN NW         30101-7197         ACWORTH    GA
9          SOPHY DR SW         30127-5541  POWDER SPRINGS    GA